server:
  port: 8888

spring:
  application:
    name: mybatis-plus
  datasource:
    username: root
    password: JJ_passwd@2017
    url: jdbc:mysql://10.1.20.11:3306/wypt_xuty?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    auto: false
#  data:
#    solr:
#      host: http://xutingyin.cn:8983/solr/
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: root
#    password: root123456

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    type-aliases-package: cn.xutingyin.mybatisplus.mapper
#      mapper-locations: classpath:mapper/*.xml