server:
  port: 8888

spring:
  application:
    name: mybatis-plus
  datasource:
    username: root
    password: root123456
    url: jdbc:mysql://127.0.0.1:3306/mworld?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    auto: false
  data:
    solr:
      host: http://xutingyin.cn:8983/solr/
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl